name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ghostwrite:
    name: Run Ghostwrite
    runs-on: ubuntu-24.04-riscv
    steps:
    - name: uname
      run: echo "hello from $(uname -m)"
    - name: lscpu
      run: lscpu
    - uses: actions/checkout@v4
    - name: build
      run: gcc -march="rv64gvzve64x" ghostwrite.c -o ghostwrite
    - name: cat-cpu
      run: head -n 9 /proc/cpuinfo
    - name: run-test
      run: sudo ./ghostwrite
